options:
  docker: true
image: softonic/cloud-sdk
clone:
  depth: 1

pipelines:
  default:
    - step:
        script:

          #-----------------------------------
          # Build tag and push the container:
          #-----------------------------------

          - export IMAGE_NAME='quay.io/softonic/tva-worker'
          - docker build -t ${IMAGE_NAME}:${BITBUCKET_COMMIT::7} .
          - docker tag ${IMAGE_NAME}:${BITBUCKET_COMMIT::7} ${IMAGE_NAME}:latest
          - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} quay.io
          - docker push ${IMAGE_NAME}

          #---------------------------------
          # Setup google cloud credentials:
          #---------------------------------

          - echo ${GCLOUD_SVCACCOUNT_KEY} | base64 -d > key.json
          - gcloud auth activate-service-account --key-file key.json
          - gcloud config set project ${GCLOUD_PROJECT}
          - gcloud container clusters get-credentials ${K8S_CLUSTER_NAME} --zone europe-west1-b --project ${GCLOUD_PROJECT}

          #-------------------------
          # Deploy the new version:
          #-------------------------

          - helm init --client-only
          - helm registry pull quay.io/softonic/thevotingapp
          - ./bin/deploy-k8s softonic_*/thevotingapp
          - helm get values thevotingapp
