options:
  docker: true

pipelines:
  default:
    - step:
        script:
          - export IMAGE_NAME=quay.io/softonic/tva-worker
          - docker build -t ${IMAGE_NAME}:${BITBUCKET_COMMIT::6} .
          - docker tag ${IMAGE_NAME}:${BITBUCKET_COMMIT::6} ${IMAGE_NAME}:latest
          - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} quay.io
          - docker push ${IMAGE_NAME}
