apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deployment-worker
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: quay.io/h0tbird/tva-worker:latest
        imagePullPolicy: Always
